config/routes.rb
Rails.application.routes.draw do

  get 'students/home'

  get 'administrators/home'

  get 'permited_teachers/index'

  get 'users/home' => 'users#home'
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  get 'users/inscription' => 'users#inscription'
  post 'users/inscription' => 'permited_teachers#create'
  get 'users/logout'
  resources :users, only: [:index, :edit, :show, :update, :destroy]
  
  resources :permited_teachers
  
  get 'teachers/home' => 'teachers#home'
  get 'teachers/invite' => 'teachers#invite'
  post 'teachers/invite' => 'invited_students#create'
  resources :teachers

  resources :notes

  resources :subjects
  get 'subjects/:id/exams' => 'subjects#exams', as: 'subject_exams'

  resources :tests
  get 'tests/:id/grade' => 'tests#grade', as: 'test_grade'
  post 'tests/:id/grade' => 'notes#create'
  patch 'tests/:id/grade' => 'notes#update'

  resources :relations
  

  root 'users#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/permited_teachers_controller.rb
class PermitedTeachersController < ApplicationController
  def create
    @permitedteacher = PermitedTeacher.create username: params[:username], password: params[:password], name: params[:name], surname: params[:surname], email: params[:email]
    if @permitedteacher.save
      flash[:notice] = "Demande d'inscription envoyée"
      redirect_to "users/home"
    else
      flash[:notice] = "Erreur"
      redirect_to users_inscription_path
    end
  end

  def index
    @permited_teachers = PermitedTeacher.all
  end

  def show
  end

  def destroy
    PermitedTeacher.find(params[:id]).delete
    redirect_to permited_teachers_index_path
  end
end

app/views/permited_teachers/index.html.haml
%div{:style => "height:4px;"}
%h2 Liste des professeurs en attente
%table.table.table-striped.table-hover
  %tr.danger
    %th NOM
    %th PRÉNOM
    %th APPROUVER
    %th REFUSER
  - @permited_teachers.each do |permited_teacher|
    %tr.info
      %td #{permited_teacher.surname}
      %td #{permited_teacher.name}
      %td 
        = link_to('Approuver', teachers_path(@teacher, :username => permited_teacher.username, :password => permited_teacher.password, :name => permited_teacher.name, :surname => permited_teacher.surname), method: :post)
      %td
        = link_to('Refuser', permited_teacher_path(permited_teacher), method: :delete, data: { confirm: 'Êtes-vous sûr?' })
= link_to('Retour', administrators_home_path)









  









  