config/routes.rb
Rails.application.routes.draw do

  get 'students/home'

  get 'administrators/home'

  get 'permited_teachers/index'

  get 'users/home' => 'users#home'
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  get 'users/inscription' => 'users#inscription'
  post 'users/inscription' => 'permited_teachers#create'
  get 'users/logout'
  resources :users, only: [:index, :edit, :show, :update, :destroy]
  
  resources :permited_teachers
  
  get 'teachers/home' => 'teachers#home'
  get 'teachers/invite' => 'teachers#invite'
  post 'teachers/invite' => 'invited_students#create'
  resources :teachers

  resources :notes

  resources :subjects
  get 'subjects/:id/exams' => 'subjects#exams', as: 'subject_exams'

  resources :tests
  get 'tests/:id/grade' => 'tests#grade', as: 'test_grade'
  post 'tests/:id/grade' => 'notes#create'
  patch 'tests/:id/grade' => 'notes#update'

  resources :relations
  

  root 'users#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy, :exams]

  # GET /subjects
  # GET /subjects.json
  def index
    logged_in
    if @current_user.teacher?
      @subjects = Subject.where(teacher_id: @current_user.id)
    elsif @current_user.student?
      @subjects = Subject.where(id: Relation.select(:subject_id).where(student_id: @current_user.id))
    else
      @subjects = Subject.all
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    if @current_user
      @students = Student.where.not(id: Relation.select(:student_id).where(subject_id: @subject.id))
      @inscrits = Student.where(id: Relation.select(:student_id).where(subject_id: @subject.id))
    else
      redirect_to request.referrer || root_path
    end
  end

  # GET /subjects/new
  def new
    teacher_exclusive
		@subject = Subject.new
  end

 # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    teacher_exclusive
    @subject = Subject.create title: params[:title], start_date: params[:start_date], end_date: params[:end_date], teacher_id: @current_user.id
	

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'La matière a été insérée' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def exams
    @exams = Test.where(subject_id: @subject.id)
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update title: params[:title], start_date: params[:start_date], end_date: params[:end_date], teacher_id: @current_user.id
        format.html { redirect_to @subject, notice: 'La matière a été modifiée' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.delete
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'La matière a été supprimée' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:index, :new, :create, :show, :update, :delete)
    end
end

app/views/subjects/edit.html.erb
<h1>Modifier <%= @subject.title%></h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Modifier', @subject %> |
<%= link_to 'Retour', subjects_path %>

app/views/subjects/exams.html.haml
%h2 Examens de #{@subject.title}

%table
  %th Titre
  %th Date

  - @exams.each do |exam|
    %tr
      %td #{exam.title}
      %td #{exam.test_date}
      %td
        = link_to('Montrer', test_path(exam))
      - if @current_user.teacher?
        %td
          = link_to('Éditer', edit_test_path(exam))
        %td
          = link_to('Supprimer', exam, method: :delete, data: { confirm: 'Êtes-vous sûr?' })
        
= link_to('Ajouter une épreuve', new_test_path)

app/views/subjects/index.html.haml
%h2 Liste des Matières

%table
  %tr
    %th Titre
    %th Date de début
    %th Date de fin
  - @subjects.each do |subject|
    %tr
      %td #{subject.title}
      %td #{subject.start_date}
      %td #{subject.end_date}
      %td 
        = link_to('Montrer', subject_path(subject))
      - if @current_user.teacher?
        %td 
          = link_to('Modifier', edit_subject_path(subject))
        %td 
          = link_to('Détruire', subject, method: :delete, data: { confirm: 'Are you sure?' })

- if @current_user.teacher?
  = link_to('Ajouter une matière', new_subject_path)

app/views/subjects/new.html.haml
%h2 Créer une matiére

= render 'form', subject: @subject

= link_to 'Retour', subjects_path

app/views/subjects/show.html.haml
%h2
  = @subject.title

%h3 Étudiants inscrits

%table
  %th Nom
  %th Prénom
  - @inscrits.each do |inscrit|
    - relation = Relation.where(student_id: inscrit.id, subject_id: @subject.id).first
    %tr
      %td #{inscrit.surname}
      %td #{inscrit.name}
      - if @current_user.teacher?
        %td
          = link_to('Enlever', relation, method: :delete, data: { confirm: 'Êtes-vous sûr?' })
    


- if @current_user.teacher?
  %h3 Ajouter des étudiants

  %table
    %th Nom
    %th Prénom

    - @students.each do |student|
      %tr
        %td #{student.surname}
        %td #{student.name}
        %td
          = link_to('Ajouter', relations_path(@relation, :student_id => student.id, :subject_id => @subject.id), method: :post)


= link_to('Modifier', edit_subject_path(@subject))
= link_to('Retour', subjects_path)
= link_to('Épreuves', subject_exams_path(@subject))