config/routes.rb
Rails.application.routes.draw do

  get 'students/home'

  get 'administrators/home'

  get 'permited_teachers/index'

  get 'users/home' => 'users#home'
  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  get 'users/inscription' => 'users#inscription'
  post 'users/inscription' => 'permited_teachers#create'
  get 'users/logout'
  resources :users, only: [:index, :edit, :show, :update, :destroy]
  
  resources :permited_teachers
  
  get 'teachers/home' => 'teachers#home'
  get 'teachers/invite' => 'teachers#invite'
  post 'teachers/invite' => 'invited_students#create'
  resources :teachers

  resources :notes

  resources :subjects
  get 'subjects/:id/exams' => 'subjects#exams', as: 'subject_exams'

  resources :tests
  get 'tests/:id/grade' => 'tests#grade', as: 'test_grade'
  post 'tests/:id/grade' => 'notes#create'
  patch 'tests/:id/grade' => 'notes#update'

  resources :relations
  

  root 'users#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_studentnav.html.haml
%nav.navbar.navbar-default{:style => "background-color:#00bfff"}
  .container-fluid
    .navbar-header 
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Page étudiant
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "http://localhost:3000/students/home"}
            Home
            %span.sr-only (current)
        %li
          = link_to('Profil', user_path(@current_user.id))
        %li
          = link_to('Épreuves', tests_path)
        %li
          = link_to('Matières', subjects_path)
        %li
          = link_to('Notes', notes_path)
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "http://localhost:3000/users/logout"} Déconnexion
      








    
     

app/views/layouts/_teachernav.html.haml
%nav.navbar.navbar-default{:style => "background-color:#00bfff"}
  .container-fluid
    .navbar-header 
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Page enseignant
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "http://localhost:3000/teachers/home"}
            Home
            %span.sr-only (current)
        %li
          = link_to('Profil', user_path(@current_user.id))
        %li
          = link_to('Inviter un étudiant', '/teachers/invite')
        %li
          = link_to('Épreuves', tests_path)
        %li
          = link_to('Matières', subjects_path)
        %li
          = link_to('Notes', notes_path)
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "http://localhost:3000/users/logout"} Déconnexion
      
          





  
 
   

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Site
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if @current_user.try(:admin?)
      = render 'layouts/adminheader'
      = render 'layouts/adminnav'
    - else
      - if @current_user.try(:teacher?)
        = render 'layouts/teacherheader'
        = render 'layouts/teachernav'
      - else
        - if @current_user.try(:student?)
          = render 'layouts/studentheader'
          = render 'layouts/studentnav'
    = flash[:notice]
    = flash[:error]
    = yield
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
    = javascript_include_tag "//https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
>